#![allow(clippy::all)]

//! Generated by `dbus-codegen` and not part of the public APIs.
//!
//! However, since this crate is already private, making everything here public is only to include
//! them in the documentation for development convenience.

pub mod ibus;
